### ISSUE TITLE
Provide proper SPARQL endpoint default configuration

### ISSUE THREAD

**Issue by ktk** [zazuko/data.admin.ch#1]
YASGUI is not properly configured to use our own SPARQL endpoint by default.

**Comment by retog** [comment]
@ktk are you working on this issue(s)? (I think it should be assigned to be marked as ready)

**Comment by ktk** [comment]
No I don't, I think we should use the chance to update trifid for that

**Comment by retog** [comment]
While waiting for a https://github.com/zazukoians/trifid-ld/issues/15 to be resolved we need a fix here. I think that s the YASGUI page will probably need some branding we have to overwrite that file here anyway.
