### ISSUE TITLE
Provide title in HTML pages

### ISSUE THREAD

**Issue by ktk** [zazuko/data.admin.ch#13]
There should be a way to replace the content of the `<title>` HTML tag via RDF. I am not completely sure which predicate we should choose, maybe [schema:about](https://schema.org/about).

**Comment by retog** [comment]
In Example 3 on https://schema.org/Article they use schema:name for the title, schema:headline and dcterms:title seem to be candidates too.

**Comment by ktk** [comment]
Both would be fine for me. Problem I see is that we do have `site:title` in our own namespace. This could be a bit confusing. Maybe it would be smarter to rename this to `site:heading` as this is rendered as a heading anyway.

Then we could use either `schema:name` or `dct:title`. If we want to stick with our namespace and schema.org I would go for `schema:name`, altough I think `dct:title` is clearer and matches with the HTML tag.
