### ISSUE TITLE
Specific matcher for resources with dbpedia abstract and image properties

### ISSUE THREAD

**Issue by retog** [zazuko/data.admin.ch#15]
There should be a matcher for resources with dbpedia abstract and image. If an abstract is available the default view showing all properties should be collapsed by default (&lt;div class="collapsed" caption="details"> {{{:continue}}}&lt;/div> (assuming a script that collapses the elements of the class "collapsed)).

The abstract should only be shown in the users preferred language, for code that shows hoe to do the language selection see: http://zazuko.github.io/lindas-datasets/

![data-admin-ch_mashup](https://cloud.githubusercontent.com/assets/110756/16245770/b14c139a-3802-11e6-8a03-f13b222827f2.png)

**Comment by alemela** [comment]
Ok, so the actual box where all the dbpedia properties are shown when the sameAs occurs remains as it is but collapsed if the new matcher is active. Right?

**Comment by retog** [comment]
@alemela, right. Note that there is nothing sameAs specific in this issue, its just a matcher for things with a <http://dbpedia.org/ontology/abstract> and <http://dbpedia.org/ontology/thumbnail> properties.

**Comment by alemela** [comment]
Okay, just to be sure, thanks!

**Comment by retog** [comment]
Currently the dbpedia data is no longer recoginizable as part of the remote owl:sameAs content. It is however important to be able to disctinguis authoritative from non-authoritative infos.

I'd like to see something like:
 

    Same resource on the linked data web: http://dbpedia.org/resource/Ossingen
     
    Summary / Picture
     
    Show more details

 
For owlSame resources without the summary I think it should be something like:
 

    Same resource on the linked data web: http://dbpedia.org/resource/Ossingen, show details.

**Comment by alemela** [comment]
Ok, I will change the interface using your schema.
