### ISSUE TITLE
Add agepiramid

### ISSUE THREAD

**Issue by retog** [zazuko/data.admin.ch#17]
The code has already been implemented in https://github.com/zazukoians/municipality-browser/issues/1. So this is just about copying over matchers and css, as well as adding d3 to graph.html

**Comment by retog** [comment]
There's aproblem with the percentages in the x-axis labelling show up duplicated, @alemela: thanks for looking into this.

**Comment by alemela** [comment]
See: https://github.com/zazukoians/municipality-browser/pull/3
