### ISSUE TITLE
Search is not working with non-ASCII characters

### ISSUE THREAD

**Issue by mchlrch** [zazuko/data.admin.ch#3]
Search interface: http://classifications.data.admin.ch/search/municipalities/

* Searching for *rüegsau* does not find http://classifications.data.admin.ch/municipality/956
* Searching for *prévondavaux* does not find http://classifications.data.admin.ch/municipality/2038

Probably related to https://github.com/zazuko/trifid/issues/38

**Comment by vhf** [comment]
https://github.com/zazuko/trifid/issues/38#issuecomment-452378787

Fixed in sparql-http-client@1.0.2 (not 1.0.3)
